### ISSUE TITLE
Unclear what is needed for development

### ISSUE THREAD

**Issue by peter-scholtens** [tweedegolf/mailcrab#18]
It's unclear for me how to start the [develop trajectory](https://github.com/tweedegolf/mailcrab#development). Apparently I need to have a ```dist``` directory created by running ```trunk build```. And also have ```rustup target add wasm32-unknown-unknown``` added. And then still it complains I need ```https://docs.rs/getrandom/latest/getrandom/#webassembly-support```. Can you add that in the description part?

**Comment by marlonbaeten** [comment]
Thank you for the feedback. A frontend build should not be necessary, but I see the app complained if `index.html` does not exists. I fixed this in the latest release.

The `wasm32-unknown-unknown` target should be present after installing Trunk, but I have added a note to the README.

I do not know why you get an error related to `getrandom` , since I do not use this dependency directly in mailcrab. Which version if Rust are you using? Do you have a more detailed error output?

Note that you should not run cargo in the frontend directory , only `trunk serve`.

**Comment by peter-scholtens** [comment]
After pulling the latest version fc82196f724e8aeea0ec1b8a07842a1785798648 the problems are gone. I can start the front-end, then the back-end then run the test, it works!
